services:
    # Frontend
    cafe-store:
        build:
            context: ./Apps/frontend
            args:
                APP_NAME: cafe-store
        image: cafe-store
        ports:
            - 8080:80

    cafe-admin:
        build:
            context: ./Apps/frontend
            args:
                APP_NAME: cafe-admin
        image: cafe-admin
        ports:
            - 8081:80

    # Backend
    cafe-service:
        build:
            context: ./Apps/backend/cafe-service
            dockerfile: Dockerfile
        image: 'cafe-service'
        restart: on-failure
        ports:
            - '3000:3000'
        volumes:
            - .:/code

    auth-service:
        build:
            context: ./Apps/backend/auth-service
            dockerfile: Dockerfile
        image: 'auth-service'
        restart: on-failure
        ports:
            - '3100:3100'
        volumes:
            - .:/code
