services:
    # Frontend
    cafe-store:
        build:
            context: ./Apps/frontend
            args:
                APP_NAME: cafe-store
                ADMIN_UI_URL: http://localhost:4201
                STORE_UI_URL: http://localhost:4200

        image: cafe-store
        container_name: cafe-store

        ports:
            - 8080:80

    cafe-admin:
        build:
            context: ./Apps/frontend
            args:
                APP_NAME: cafe-admin
                ADMIN_UI_URL: http://localhost:4201
                STORE_UI_URL: http://localhost:4200

        image: cafe-admin
        container_name: cafe-admin

        ports:
            - 8081:80

    # Backend
    cafe-service:
        build:
            context: ./Apps/backend/cafe-service
            dockerfile: Dockerfile

        image: cafe-service
        container_name: cafe-service
        restart: on-failure

        ports:
            - '3000:3000'

        environment:
            - APP_ENV
            - PORT
            - ACCESS_TOKEN
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - AWS_ENDPOINT_URL

    auth-service:
        build:
            context: ./Apps/backend/auth-service
            dockerfile: Dockerfile

        image: auth-service
        container_name: auth-service
        restart: on-failure

        ports:
            - '3100:3100'

        environment:
            - APP_ENV
            - PORT
            - ACCESS_TOKEN_SECRET
            - REFRESH_TOKEN_SECRET
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - AWS_ENDPOINT_URL

    rt-gateway:
        build:
            context: ./Apps/backend/realtime-gateway
            dockerfile: Dockerfile

        image: rt-gateway
        container_name: rt-gateway
        restart: on-failure

        ports:
            - '3200:3200'

        environment:
            - CORS_ORIGINS
            - REALTIME_GATEWAY_ENDPOINT_URL
            - BREVO_BASE_URL
            - ADMIN_UI_URL
            - STORE_UI_URL
            - SMTP_CONFIG
